dcgm-exporter:
  runtimeClassName: nvidia
  nodeSelector:
    nvidia.com/gpu.present: "true"
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceMonitor:
    enabled: true
    interval: 30s
