---
# ArgoCD Application for Monitoring Stack
# This is the proper way to deploy Helm charts with ArgoCD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    type: infrastructure
spec:
  project: homelab
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 77.6.2
    helm:
      values: |
        # Grafana Configuration
        grafana:
          enabled: true
          adminPassword: "admin"
          service:
            type: LoadBalancer
            port: 80
            targetPort: 3000
          persistence:
            enabled: true
            size: 1Gi
            storageClassName: longhorn
          defaultDashboardsEnabled: true
          plugins:
            - grafana-piechart-panel
            - grafana-worldmap-panel

        # Prometheus Configuration
        prometheus:
          enabled: true
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            retention: 200h
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
            service:
              type: LoadBalancer
              port: 80
              targetPort: 9090
            securityContext:
              runAsUser: 65534
              runAsGroup: 65534
              runAsNonRoot: true
              fsGroup: 65534

        # Disable Alertmanager for simplicity
        alertmanager:
          enabled: false

        # Enable essential components
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
        kubelet:
          enabled: true
        kubeApiServer:
          enabled: true
        kubeControllerManager:
          enabled: true
        kubeScheduler:
          enabled: true
        kubeProxy:
          enabled: true
        kubeEtcd:
          enabled: true
        coreDns:
          enabled: true
        kubeDns:
          enabled: true

        # Monitor homelab services
        additionalServiceMonitors:
          - name: "homelab-services"
            selector:
              matchLabels:
                prometheus.io/scrape: "true"
            namespaceSelector:
              matchNames:
                - "homepage"
                - "n8n"
                - "cloudflare-tunnel"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
