apiVersion: apps/v1
kind: Deployment
metadata:
  name: catbag
  namespace: catbag
  labels:
    app: catbag
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: catbag
  template:
    metadata:
      labels:
        app: catbag
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: nginx
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: site
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 50m
      volumes:
        - name: site
          configMap:
            name: catbag-html
            items:
              - key: index.html
                path: index.html
        - name: nginx-config
          configMap:
            name: catbag-html
            items:
              - key: nginx.conf
                path: nginx.conf


