apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: github-runner-auth
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-auth-sa
        namespace: infisical-operator-system
      secretsScope:
        projectSlug: "homelab-k8s"
        envSlug: "prod"
        secretsPath: "/github-runners"
  managedSecretReference:
    secretName: github-runner-auth
    creationPolicy: Owner
    secretType: Opaque
