{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: velero-credentials
spec:
  resyncInterval: {{ .Values.infisical.resyncInterval }}
  authentication:
    kubernetesAuth:
      identityId: {{ .Values.infisical.identityId | quote }}
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-auth-sa
        namespace: infisical-operator-system
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug | quote }}
        envSlug: {{ .Values.infisical.envSlug | quote }}
        secretsPath: {{ .Values.infisical.secretsPath | quote }}
  managedSecretReference:
    secretName: velero-credentials
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Owner
    secretType: Opaque
{{- end }}
