{{- if .Values.resourcePolicy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-resource-policy
  namespace: {{ .Release.Namespace }}
data:
  policy.yaml: |
    version: v1
    volumePolicies:
    - conditions:
        volumeTypes:
        - nfs
      action:
        type: skip
    - conditions:
        volumeTypes:
        - persistentVolumeClaim
      action:
        type: fs-backup
{{- end }}
