apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Homelab Dashboard
    favicon: https://gethomepage.dev/img/favicon.ico
    theme: dark
    color: blue
    headerStyle: boxedWidgets
    fullWidth: true
    useEqualHeights: true
    showStats: true
    statusStyle: "dot"
    hideErrors: true
    instanceName: internal
    # Enhanced background with better readability
    background:
      image: https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2560&q=80
      opacity: 30
      brightness: 40
      saturate: 120
    cardBlur: lg
    providers:
      longhorn:
        url: https://longhorn.buildin.group
    layout:
      Infrastructure:
        style: row
        columns: 3
      Applications:
        style: row
        columns: 3
      Monitoring:
        style: row
        columns: 2
  services.yaml: |
    # All services with ingress annotations will be automatically discovered
    # Only add services here that don't have ingresses or need special configuration
    
    # Public apps (no ingress) are added manually below
    - Applications:
        - N8N:
            icon: n8n.png
            href: "https://n9n.buildin.group"
            description: Workflow automation
            namespace: n8n
            app: n8n
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - longhorn:
        expanded: true
        total: true
        nodes: true
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hour12: false
    - openmeteo:
        label: Weather
        latitude: 31.7683
        longitude: 35.2137
        timezone: Asia/Jerusalem
        cache: 5
  bookmarks.yaml: |
    # Bookmarks are automatically discovered from ingresses with gethomepage.dev annotations
    # No manual configuration needed for services with proper ingress annotations
  kubernetes.yaml: |
    mode: default
    ingress: true
    traefik: false
    # Enable only if Gateway API CRDs are installed in the cluster
    gateway: false
    # Auto-discover services from ingresses with gethomepage.dev annotations
    # Services will be automatically discovered and grouped by their annotations
  custom.css: |
    /* Enhanced readability styles */
    
    /* Improve card background contrast */
    .service-card, .bookmark-card {
      background: rgba(0, 0, 0, 0.75) !important;
      backdrop-filter: blur(20px) !important;
      border: 1px solid rgba(255, 255, 255, 0.1) !important;
    }
    
    /* Enhance text contrast */
    .service-card .service-title,
    .bookmark-card .bookmark-title {
      color: #ffffff !important;
      text-shadow: 0 1px 3px rgba(0, 0, 0, 0.8) !important;
    }
    
    .service-card .service-description,
    .bookmark-card .bookmark-description {
      color: #e0e0e0 !important;
      text-shadow: 0 1px 2px rgba(0, 0, 0, 0.6) !important;
    }
    
    /* Improve header readability */
    .header-title {
      text-shadow: 0 2px 4px rgba(0, 0, 0, 0.8) !important;
    }
    
    /* Enhance widget text */
    .widget-content {
      color: #ffffff !important;
      text-shadow: 0 1px 2px rgba(0, 0, 0, 0.7) !important;
    }
    
    /* Improve status indicators */
    .status-dot {
      box-shadow: 0 0 8px rgba(0, 255, 0, 0.5) !important;
    }
  custom.js: |
    // Custom JavaScript for Homepage
    // Add your custom scripts here