apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Homelab Dashboard
    favicon: https://gethomepage.dev/img/favicon.ico
    theme: dark
    color: blue
    headerStyle: boxedWidgets
    fullWidth: true
    useEqualHeights: true
    showStats: true
    statusStyle: "dot"
    hideErrors: true
    instanceName: internal
    # Subtle blue background inspired by docs example
    background: https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2560&q=80
    backgroundOpacity: 0.25
    backgroundBlur: 4
    cardBackgroundBlur: 2
    providers:
      longhorn:
        url: https://longhorn.buildin.group
    layout:
      Infrastructure:
        style: row
        columns: 3
      Applications:
        style: row
        columns: 3
      Monitoring:
        style: row
        columns: 2
  skeleton-settings.yaml: |
    title: Homelab Dashboard
    favicon: https://gethomepage.dev/img/favicon.ico
    theme: dark
    color: blue
    headerStyle: boxedWidgets
    fullWidth: true
    useEqualHeights: true
    showStats: true
    statusStyle: "dot"
    hideErrors: true
    background: https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2560&q=80
    backgroundOpacity: 0.25
    backgroundBlur: 4
    cardBackgroundBlur: 2
  services.yaml: |
    # All services with ingress annotations will be automatically discovered
    # Only add services here that don't have ingresses or need special configuration
    
    # Services are automatically discovered from ingresses with gethomepage.dev annotations
    # No manual configuration needed for services with proper ingress annotations
  widgets.yaml: |
    # Header widgets - organized in logical groups
    - logo:
        icon: https://gethomepage.dev/img/favicon.ico
    # Prioritize key stats up front for a cleaner, data-first header
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - longhorn:
        expanded: true
        total: true
        nodes: true
    # Utility and context widgets to the right
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hour12: false
    - openmeteo:
        label: Weather
        latitude: 31.7683
        longitude: 35.2137
        timezone: Asia/Jerusalem
        cache: 5
    - greeting:
        text_size: m
        text: "Welcome to your Homelab!"
  bookmarks.yaml: |
    # Bookmarks are automatically discovered from ingresses with gethomepage.dev annotations
    # No manual configuration needed for services with proper ingress annotations
  kubernetes.yaml: |
    mode: default
    ingress: true
    traefik: false
    # Enable only if Gateway API CRDs are installed in the cluster
    gateway: false
    # Auto-discover services from ingresses with gethomepage.dev annotations
    # Services will be automatically discovered and grouped by their annotations
  custom.css: |
    /* Custom CSS for Homepage */
    /* Add your custom styles here */
  custom.js: |
    // Custom JavaScript for Homepage
    // Add your custom scripts here