---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "homepage.buildin.group"
    exposure.service-controller.io/type: "public"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: homepage
