---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
  annotations:
    external-dns.alpha.kubernetes.io/hostname: homepage.buildin.group
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: homepage
