apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "homepage.buildin.group"
    exposure.service-controller.io/type: "public"
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: homepage
