app-blueprint:
  image:
    repository: devlikeapro/waha
    tag: "noweb-2026.3.4"

  containerPort: 3000

  dns:
    hostname: waha.ganam.app
    exposure: internal

  homepage:
    name: "WAHA"
    description: "WhatsApp HTTP API"
    icon: "whatsapp.png"

  volumes:
    - name: sessions
      size: 128Mi
      mountPath: /app/.sessions
    - name: media
      size: 512Mi
      mountPath: /app/.media

  infisical:
    enabled: true
    identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
    secretsPath: "/waha"
    secretName: waha-secret

  env:
    WHATSAPP_DEFAULT_ENGINE: "NOWEB"

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  probes:
    liveness:
      path: "/ping"
    readiness:
      path: "/ping"

  resources:
    requests:
      cpu: 10m
      memory: 512Mi
    limits:
      cpu: 30m
      memory: 2Gi
