# Values to override the upstream Stirling-PDF chart

stirling-pdf-chart:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent


  service:
    type: ClusterIP
    externalPort: 8080
    annotations: {}
    labels:
      dns.service-controller.io/enabled: "true"
      dns.service-controller.io/hostname: pdf.buildin.group
      exposure.service-controller.io/type: internal

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      # Homepage automatic service discovery annotations
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Stirling PDF"
      gethomepage.dev/description: "PDF Toolbox"
      gethomepage.dev/icon: "stirling-pdf.png"
      gethomepage.dev/group: "Applications"
      gethomepage.dev/weight: "25"
      gethomepage.dev/pod-selector: "app.kubernetes.io/name=stirling-pdf-chart,app.kubernetes.io/instance=stirling-pdf"
    hosts:
      - name: pdf.buildin.group
        path: /
        tls: false

  persistence:
    enabled: true
    size: 256Mi
    accessMode: ReadWriteOnce
    storageClass: longhorn
    path: /configs

  envs:
    - name: UI_APP_NAME
      value: "Stirling PDF"
    - name: UI_HOME_DESCRIPTION
      value: "Local PDF toolbox"
    - name: APP_LOCALE
      value: "en_GB"

  resources:
    requests:
      cpu: 7m
      memory: 320Mi
    limits:
      cpu: 9m
      memory: 437Mi


  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 12
    readiness:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 12


