---
# This file is a template - you need to replace the placeholder values
# with your actual Cloudflare API token and Zone ID
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
type: Opaque
data:
  # Replace with your base64 encoded Cloudflare API token
  # To get your token: https://dash.cloudflare.com/profile/api-tokens
  # To encode: echo -n "your-token" | base64
  cloudflare_api_token: Q0hBTkdFX01F  # This is "CHANGE_ME" encoded
