---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - namespace.yaml
  - external-dns-deployment.yaml
  - external-dns-rbac.yaml
  - create-dns-records.yaml
