---
apiVersion: v1
kind: Service
metadata:
  name: CHANGEME  # Replace with your app name
  namespace: CHANGEME  # Replace with your app name
  labels:
    app: CHANGEME  # Replace with your app name
  annotations:
    external-dns.alpha.kubernetes.io/hostname: CHANGEME.yourdomain.com  # Replace with your domain
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ClusterIP  # Use ClusterIP with Cloudflare Tunnel
  ports:
  - name: http
    port: 80  # External port
    targetPort: 80  # Replace with your app's container port
    protocol: TCP
  selector:
    app: CHANGEME  # Replace with your app name
