apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cert-manager-webhook
  annotations:
    argocd.argoproj.io/ignore-differences: |
      jsonPointers:
      - /webhooks/0/clientConfig/caBundle
