apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-internal
  namespace: ingress-nginx
spec:
  secretName: wildcard-internal-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - "*.buildin.group"
    - "*.ganam.app"
