apiVersion: v2
name: github-runners
description: GitHub Actions Runner Scale Set
type: application
version: 0.1.0
appVersion: "0.9.3"
dependencies:
  - name: gha-runner-scale-set
    version: 0.14.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
