gha-runner-scale-set:
  githubConfigUrl: "https://github.com/ronganam/homelab"
  githubConfigSecret: github-runner-auth
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-systems-gha-rs-controller
  minRunners: 0
  maxRunners: 5
  runnerScaleSetName: "selfhosted-homelab"
