kube-prometheus-stack:
  # Disable admission controller to fix ArgoCD compatibility
  admissionWebhooks:
    enabled: false
  
  # Disable pre-upgrade hooks for ArgoCD compatibility
  preUpgradeHook:
    enabled: false
  
  grafana:
    enabled: true
    adminPassword: "admin"
    service:
      type: LoadBalancer
      port: 80
      targetPort: 3000
      labels:
        dns.service-controller.io/enabled: "true"
        dns.service-controller.io/hostname: grafana.buildin.group
        exposure.service-controller.io/type: internal
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: longhorn
    defaultDashboardsEnabled: true
    plugins:
      - grafana-piechart-panel
      - grafana-worldmap-panel
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'longhorn-dashboards'
          orgId: 1
          folder: 'Longhorn'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/longhorn
    dashboards:
      longhorn:
        longhorn-dashboard:
          gnetId: 22705
          revision: 1
          datasource: Prometheus

  prometheus:
    enabled: true
    service:
      type: LoadBalancer
      port: 80
      targetPort: 9090
      labels:
        dns.service-controller.io/enabled: "true"
        dns.service-controller.io/hostname: prometheus.buildin.group
        exposure.service-controller.io/type: internal
    additionalServiceMonitors:
      - name: "homelab-services"
        selector:
          matchLabels:
            prometheus.io/scrape: "true"
        namespaceSelector:
          matchNames:
            - "homepage"
            - "n8n"
            - "cloudflare-tunnel"
      - name: "longhorn-monitoring"
        selector:
          matchLabels:
            app: longhorn-manager
        namespaceSelector:
          matchNames:
            - "longhorn-system"
        endpoints:
          - port: manager
            path: /metrics
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      retention: 200h
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        fsGroup: 65534

  # Disable Alertmanager for simplicity
  alertmanager:
    enabled: false

  # Enable essential components
  nodeExporter:
    enabled: true

  kubeStateMetrics:
    enabled: true

  kubelet:
    enabled: true
  kubeApiServer:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true
  kubeEtcd:
    enabled: true
  coreDns:
    enabled: true
  kubeDns:
    enabled: true

  # (moved) additionalServiceMonitors now live under kube-prometheus-stack.prometheus
