kube-prometheus-stack:
  # Disable admission controller to fix ArgoCD compatibility
  admissionWebhooks:
    enabled: false
  # Disable pre-upgrade hooks for ArgoCD compatibility
  preUpgradeHook:
    enabled: false
  grafana:
    enabled: true
    adminPassword: "admin"
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.buildin.group
    service:
      type: ClusterIP
      port: 80
      targetPort: 3000
      labels:
        dns.service-controller.io/enabled: "true"
        dns.service-controller.io/hostname: grafana.buildin.group
        exposure.service-controller.io/type: internal
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: longhorn
    defaultDashboardsEnabled: true
    plugins:
      - grafana-piechart-panel
      - grafana-worldmap-panel
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'longhorn-dashboards'
            orgId: 1
            folder: 'Longhorn'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/longhorn
    dashboards:
      longhorn:
        longhorn-dashboard:
          gnetId: 17626
          revision: 1
          datasource: Prometheus
          inputs:
            - name: DS_PROMETHEUS
              type: datasource
              pluginId: prometheus
              value: Prometheus
  prometheus:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.buildin.group
    service:
      type: ClusterIP
      port: 80
      targetPort: 9090
      labels:
        dns.service-controller.io/enabled: "true"
        dns.service-controller.io/hostname: prometheus.buildin.group
        exposure.service-controller.io/type: internal
    additionalServiceMonitors:
      - name: "longhorn-monitoring"
        selector:
          matchLabels:
            app: longhorn-manager
        namespaceSelector:
          matchNames:
            - "longhorn-system"
        endpoints:
          - port: manager
            path: /metrics
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      retention: 7d
      retentionSize: 2GiB
      walCompression: true
      additionalArgs:
        - name: storage.tsdb.min-block-duration
          value: "30m"
        - name: storage.tsdb.max-block-duration
          value: "30m"
        - name: storage.tsdb.wal-segment-size
          value: "64MB"
        - name: storage.tsdb.head-chunks-write-queue-size
          value: "1000"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 4Gi
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        fsGroup: 65534
  # Disable Alertmanager for simplicity
  alertmanager:
    enabled: false
  # Enable essential components
  nodeExporter:
    enabled: true
  kubeStateMetrics:
    enabled: true
  kubelet:
    enabled: true
  kubeApiServer:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true
  kubeEtcd:
    enabled: true
  coreDns:
    enabled: true
  kubeDns:
    enabled: true

# (moved) additionalServiceMonitors now live under kube-prometheus-stack.prometheus
