kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: "admin"
    service:
      type: LoadBalancer
      port: 80
      targetPort: 3000
      labels:
        dns.service-controller.io/enabled: "true"
        dns.service-controller.io/hostname: grafana.buildin.group
        exposure.service-controller.io/type: internal
    persistence:
      enabled: false
      size: 1Gi
      storageClassName: longhorn
    defaultDashboardsEnabled: true
    plugins:
      - grafana-piechart-panel
      - grafana-worldmap-panel

  prometheus:
    enabled: true
    service:
      type: LoadBalancer
      port: 80
      targetPort: 9090
      labels:
        dns.service-controller.io/enabled: "true"
        dns.service-controller.io/hostname: prometheus.buildin.group
        exposure.service-controller.io/type: internal
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      retention: 200h
      storageSpec: {}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        fsGroup: 65534

  # Disable Alertmanager for simplicity
  alertmanager:
    enabled: false

  # Enable essential components
  nodeExporter:
    enabled: true

  kubeStateMetrics:
    enabled: true

  kubelet:
    enabled: true
  kubeApiServer:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true
  kubeEtcd:
    enabled: true
  coreDns:
    enabled: true
  kubeDns:
    enabled: true

  # Monitor homelab services
  additionalServiceMonitors:
    - name: "homelab-services"
      selector:
        matchLabels:
          prometheus.io/scrape: "true"
      namespaceSelector:
        matchNames:
          - "homepage"
          - "n8n"
          - "cloudflare-tunnel"
