app-blueprint:
  image:
    repository: registry.ganam.app/gilartworks-store
    tag: "0.4.0"

  containerPort: 3000

  dns:
    hostname: store.gilartworks.com
    exposure: internal

  ingress:
    proxyBodySize: "200m"

  homepage:
    enabled: true
    name: "GilArtworks Store"
    group: "Creative"
    icon: "material-symbols:storefront-outline"

  volumes:
    - name: uploads-local
      size: 2Gi
      mountPath: /app/public/uploads
      storageClass: local-path
    - name: database-local
      size: 128Mi
      mountPath: /app/db
      storageClass: local-path

  infisical:
    enabled: true
    identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
    secretsPath: "/gilartworks-store"
    secretName: gilartworks-store-secret

  env:
    NODE_ENV: "production"
    DATABASE_URL: "file:/app/db/dev.db"
    BODY_SIZE_LIMIT: "200mb"

  extraEnv:
    - name: ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: gilartworks-store-secret
          key: ADMIN_PASSWORD

  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    fsGroupChangePolicy: OnRootMismatch

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
