longhorn:
  preUpgradeChecker:
    jobEnabled: false
    upgradeVersionCheck: true

  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1

  csi:
    kubeletRootDir: /var/lib/kubelet

  defaultSettings:
    defaultDataPath: /var/lib/longhorn/
    replicaSoftAntiAffinity: true
    storageOverProvisioningPercentage: 200
    storageMinimalAvailablePercentage: 25
    upgradeChecker: false
    defaultReplicaCount: 1
    guaranteedInstanceManagerCPU: 12

  extraObjects:
    - apiVersion: v1
      kind: Service
      metadata:
        name: longhorn-ui-lb
        labels:
          dns.service-controller.io/enabled: "true"
          dns.service-controller.io/hostname: "longhorn.buildin.group"
          exposure.service-controller.io/type: "internal"
      spec:
        type: LoadBalancer
        ports:
          - name: http
            port: 80
            targetPort: 8000
        selector:
          app: longhorn-ui
