{{- range .Values.volumes }}
{{- if and (not .hostPath) (not .nfs) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.name" $ }}-{{ .name }}
  namespace: {{ include "app.namespace" $ }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass | default "longhorn" }}
{{- end }}
{{- end }}
