apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kan-postgres
  namespace: kan
  labels:
    app: kan-postgres
spec:
  serviceName: kan-postgres
  replicas: 1
  selector:
    matchLabels:
      app: kan-postgres
  template:
    metadata:
      labels:
        app: kan-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - name: pg
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: kan_db
            - name: POSTGRES_USER
              value: kan
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kan-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["sh", "-lc", "pg_isready -U kan -d kan_db"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
