apiVersion: apps/v1
kind: Deployment
metadata:
  name: blinko
  namespace: blinko
  labels:
    app: blinko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blinko
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blinko
        app: blinko
    spec:
      containers:
        - name: blinko
          image: blinkospace/blinko:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1111
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: blinko-secrets
                  key: nextauth_secret
                  optional: true
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: blinko-secrets
                  key: database_url
          resources:
            requests:
              cpu: 1m
              memory: 191Mi
            limits:
              cpu: 2m
              memory: 261Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3


