apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: blinko
  labels:
    app: blinko-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: blinko-postgres
  template:
    metadata:
      labels:
        app: blinko-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          imagePullPolicy: IfNotPresent
          ports:
            - name: pg
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blinko-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blinko-postgres
                  key: password
            - name: TZ
              value: Asia/Jerusalem
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["sh","-lc","pg_isready -U \"$(echo $POSTGRES_USER)\" -d \"$(echo $POSTGRES_DB)\""]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
        storageClassName: longhorn


