app-blueprint:
  image:
    repository: ronganam/gilartworks-coming-soon
    tag: v1

  dns:
    hostname: soon.gilartworks.com
    exposure: internal

  homepage:
    enabled: false

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 30m
      memory: 32Mi

  probes:
    liveness:
      initialDelaySeconds: 10
    readiness:
      initialDelaySeconds: 3
