apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

resources:
  - https://github.com/envoyproxy/gateway/releases/download/v1.7.2/install.yaml

# We might want to patch some things here if needed.
