apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - backup-configmap.yaml
  - backup-cronjob.yaml
namespace: bitwarden
