apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "bitwarden.buildin.group"
    exposure.service-controller.io/type: "internal"
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    - name: websocket
      port: 3012
      targetPort: 3012
      protocol: TCP
  selector:
    app: bitwarden
