apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
spec:
  serviceName: bitwarden
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.34.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 3012
              name: websocket
              protocol: TCP
          envFrom:
            - configMapRef:
                name: bitwarden
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-admin
                  key: token
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-smtp
                  key: username
                  optional: true
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-smtp
                  key: password
                  optional: true
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tls-certs
              mountPath: /tls
              readOnly: true
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: https
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: https
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: tls-certs
          secret:
            secretName: vaultwarden-tls
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
