fullnameOverride: "kaneo"
autoscaling:
  enabled: false
serviceAccount:
  create: true
  annotations: {}
  name: ""

infisical:
  enabled: true
  identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
  secretsPath: "/kaneo"
  secretName: "kaneo-secret"
  projectSlug: "homelab-k8s"
  envSlug: "prod"

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  auth:
    database: "kaneo"
    username: "kaneo"
    existingSecret: "kaneo-secret"
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: POSTGRES_PASSWORD
  persistence:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClass: local-path
  service:
    type: ClusterIP
    port: 5432
  resources: {}

api:
  image:
    repository: ghcr.io/usekaneo/api
    tag: "2.6.9"
    pullPolicy: IfNotPresent
  securityContext: {}
  service:
    type: ClusterIP
    port: 1337
    targetPort: 1337
  resources: {}
  env:
    KANEO_API_URL: "https://kaneo.ganam.app/api"
    KANEO_CLIENT_URL: "https://kaneo.ganam.app"
    existingSecret:
      enabled: true
      name: "kaneo-secret"
      key: "AUTH_SECRET"
    disableRegistration: false
    disablePasswordRegistration: false
    database:
      external:
        enabled: false
  livenessProbe:
    httpGet:
      path: /api/health
      port: api
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /api/health
      port: api
    initialDelaySeconds: 5
    periodSeconds: 10

web:
  image:
    repository: ghcr.io/usekaneo/web
    tag: "2.6.9"
    pullPolicy: IfNotPresent
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
    targetPort: 5173
    labels:
      dns.service-controller.io/enabled: "true"
      dns.service-controller.io/hostname: "kaneo.ganam.app"
      exposure.service-controller.io/type: "internal"
  resources: {}
  env:
    apiUrl: "https://kaneo.ganam.app"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Kaneo"
    gethomepage.dev/description: "Kanban board"
    gethomepage.dev/icon: "si-kanban"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/weight: "10"
  hosts:
    - host: kaneo.ganam.app
      paths:
        - path: /api
          pathType: Prefix
          service: api
          port: 1337
        - path: /
          pathType: Prefix
          service: web
          port: 80
  tls: []

gateway:
  enabled: false
