apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.2/deploy/static/provider/cloud/deploy.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ingress-nginx-controller
    path: controller-args-add-default-cert.json
