apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: papra-infisical-secret
  namespace: papra
spec:
  hostAPI: https://infisical.ganam.app
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      # The Identity ID from Infisical (Access Control -> Identities -> <Your Identity>)
      identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c" # TODO: Replace this with the actual Identity ID for Papra
      
      # Automatically create a token for the service account (Required for K8s 1.24+)
      autoCreateServiceAccountToken: true

      # The Service Account to use for authentication
      serviceAccountRef:
        name: default        
        namespace: papra
        
      secretsScope:
        projectSlug: "homelab-k8s"
        envSlug: "prod"
        secretsPath: "/papra"

  managedSecretReference:
    secretName: papra-secret
    secretNamespace: papra
    creationPolicy: Owner
    secretType: Opaque
