app-blueprint:
  image:
    repository: ghcr.io/papra-hq/papra
    tag: 26.2.2-rootless

  containerPort: 1221

  dns:
    hostname: papra.ganam.app
    exposure: internal

  homepage:
    name: Papra
    description: Document Management System
    icon: papra.png

  volumes:
    - name: data
      size: 1Gi
      mountPath: /app/app-data

  infisical:
    enabled: true
    identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
    secretsPath: "/papra"
    secretName: papra-secret

  env:
    APP_BASE_URL: "https://papra.ganam.app"
    AUTH_IS_REGISTRATION_ENABLED: "true"
    AUTH_IS_PASSWORD_RESET_ENABLED: "true"
    AUTH_IS_EMAIL_VERIFICATION_REQUIRED: "false"
    AUTH_SHOW_LEGAL_LINKS: "false"
    AUTH_PROVIDERS_EMAIL_IS_ENABLED: "true"
    AUTH_PROVIDERS_GITHUB_IS_ENABLED: "false"
    AUTH_PROVIDERS_GOOGLE_IS_ENABLED: "false"
    DATABASE_URL: "file:./app-data/db/db.sqlite"
    DOCUMENT_STORAGE_DRIVER: "filesystem"
    DOCUMENT_STORAGE_FILESYSTEM_ROOT: "./app-data/documents"
    DOCUMENT_STORAGE_MAX_UPLOAD_SIZE: "50000000"
    DOCUMENTS_OCR_LANGUAGES: "eng"
    DOCUMENTS_DELETED_DOCUMENTS_RETENTION_DAYS: "30"
    EMAILS_DRIVER: "logger"
    INGESTION_FOLDER_IS_ENABLED: "false"
    IS_FREE_PLAN_UNLIMITED: "true"
    MAX_ORGANIZATION_COUNT_PER_USER: "10"
    ORGANIZATION_INVITATION_EXPIRATION_DELAY_DAYS: "7"
    MAX_USER_ORGANIZATIONS_INVITATIONS_PER_DAY: "30"
    POSTHOG_ENABLED: "false"

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
