apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - templates/httproute.yaml

helmCharts:
  - name: cilium
    releaseName: cilium
    version: 1.16.1
    repo: https://helm.cilium.io/
    valuesFile: values.yaml

patches:
  - target:
      kind: Service
      name: hubble-ui
    patch: |-
      - op: add
        path: /metadata/labels/dns.service-controller.io~1enabled
        value: "true"
      - op: add
        path: /metadata/labels/dns.service-controller.io~1hostname
        value: "hubble.ganam.app"
      - op: add
        path: /metadata/labels/exposure.service-controller.io~1type
        value: "internal"
