metrics-server:
  # Deploy into kube-system as per official chart default
  replicaCount: 1
  image:
    repository: registry.k8s.io/metrics-server/metrics-server
    pullPolicy: IfNotPresent
  args:
    # Recommended flags per official chart for most clusters
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
  service:
    port: 443
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 300Mi


