infisical:
  enabled: true
  identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
  projectSlug: "homelab-k8s"
  envSlug: "prod"
  secretsPath: "/matomo"
  resyncInterval: 60

matomo:
  matomoUsername: "admin"
  existingSecret: "matomo-mariadb"
  matomoEmail: "admin@ganam.app"

  mariadb:
    enabled: true
    architecture: standalone
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: latest
    auth:
      existingSecret: "matomo-mariadb"
      database: "bitnami_matomo"
      username: "bn_matomo"
    primary:
      persistence:
        enabled: true
        storageClass: "local-path"
        size: 1Gi

  persistence:
    enabled: true
    storageClass: "local-path"
    size: 1Gi

  service:
    type: ClusterIP
    labels:
      dns.service-controller.io/enabled: "true"
      dns.service-controller.io/hostname: "matomo.ganam.app"
      exposure.service-controller.io/type: "internal"

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: matomo.ganam.app
    path: /
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Matomo"
      gethomepage.dev/description: "Web Analytics"
      gethomepage.dev/icon: "matomo.png"
      gethomepage.dev/group: "Monitoring"
      gethomepage.dev/weight: "10"
