app-blueprint:
  image:
    repository: ghcr.io/donkie/spoolman
    tag: "0.23.1"

  containerPort: 8000
  enableServiceLinks: false

  dns:
    hostname: spoolman.ganam.app
    exposure: internal

  homepage:
    name: Spoolman
    description: Filament inventory management
    icon: spoolman.png

  volumes:
    - name: data-local
      size: 128Mi
      mountPath: /home/app/.local/share/spoolman
      storageClass: local-path

  env:
    TZ: "Asia/Jerusalem"
    PUID: "1000"
    PGID: "1000"

  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  resources:
    requests:
      cpu: "10m"
      memory: "148Mi"
    limits:
      memory: "175Mi"

  probes:
    liveness:
      path: "/api/v1/health"
    readiness:
      path: "/api/v1/health"
