# Values to override the upstream Frigate chart

frigate:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/blakeblackshear/frigate
    tag: "0.16.1-tensorrt"

  service:
    type: ClusterIP
    port: 5000
    annotations: {}
    labels:
      dns.service-controller.io/enabled: "true"
      dns.service-controller.io/hostname: frigate.buildin.group
      exposure.service-controller.io/type: internal

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Frigate"
      gethomepage.dev/description: "NVR with realtime object detection"
      gethomepage.dev/icon: "frigate.png"
      gethomepage.dev/group: "Applications"
      gethomepage.dev/weight: "20"
      gethomepage.dev/pod-selector: "app.kubernetes.io/name=frigate,app.kubernetes.io/instance=frigate"
    hosts:
      - host: frigate.buildin.group
        paths:
          - path: /
            pathType: Prefix
            servicePort: 5000

  # GPU configuration (NVIDIA)
  gpu:
    nvidia:
      enabled: true
      runtimeClassName: nvidia

  # Persistent storage
  persistence:
    media:
      enabled: true
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    config:
      enabled: true
      size: 100Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn
      ephemeralWritableConfigYaml: true

  # Example Frigate configuration (adjust to your environment)
  config: |
    mqtt:
      host: "mqtt.buildin.group"
      port: 1883
      user: "frigate"
      password: "change-me"
    
    detectors:
      onnx:
        type: onnx

    ffmpeg:
      hwaccel_args: preset-nvidia

    go2rtc:
      streams:
        front_door:
          - ffmpeg:http://192.168.1.250/flv?port=1935&app=bcs&stream=channel7_main.bcs&user=viewer&password=HAViewer   # channel numbers are 0-15
          - ffmpeg:front_door#audio=aac
        front_door_sub:
          - ffmpeg:http://192.168.1.250/flv?port=1935&app=bcs&stream=channel7_ext.bcs&user=viewer&password=HAViewer

    cameras:
      front_door:
        record:
          enabled: true
        detect:
          enabled: true
          width: 640
          height: 480
        objects:
          track:
            - person
            - dog
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
              input_args: preset-rtsp-restream
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/front_door_sub?video=copy
              input_args: preset-rtsp-restream
              roles:
                - detect

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 4Gi
      nvidia.com/gpu: 1

  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 12
    readiness:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 12


