longhorn:
  preUpgradeChecker:
    jobEnabled: false
    upgradeVersionCheck: true
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
  csi:
    kubeletRootDir: /var/lib/kubelet
  defaultSettings:
    defaultDataPath: /var/lib/longhorn/
    replicaSoftAntiAffinity: true
    storageOverProvisioningPercentage: "200"
    storageMinimalAvailablePercentage: "25"
    upgradeChecker: false
    defaultReplicaCount: '{"v1":"1","v2":"1"}'
    guaranteedInstanceManagerCPU: '{"v1":"12","v2":"12"}'
  defaultBackupStore:
    backupTarget: s3://homelab-ganam@il-jerusalem-1/
    backupTargetCredentialSecret: longhorn-oci-s3-secret
    pollInterval: 300
  extraObjects:
    - apiVersion: v1
      kind: Service
      metadata:
        name: longhorn-ui
        labels:
          app.kubernetes.io/name: longhorn-ui
          dns.service-controller.io/enabled: "true"
          dns.service-controller.io/hostname: "longhorn.buildin.group"
          exposure.service-controller.io/type: "internal"
      spec:
        type: ClusterIP
        ports:
          - name: http
            port: 80
            targetPort: 8000
        selector:
          app: longhorn-ui
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: longhorn-ui
        annotations:
          kubernetes.io/ingress.class: nginx
          # Homepage automatic service discovery annotations
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Longhorn"
          gethomepage.dev/description: "Distributed Block Storage"
          gethomepage.dev/icon: "longhorn.png"
          gethomepage.dev/group: "Infrastructure"
          gethomepage.dev/weight: "2"
      spec:
        rules:
          - host: longhorn.buildin.group
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: longhorn-ui
                      port:
                        number: 80


