apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yermi-db-pvc
  namespace: yermi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
