{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "kaneo.fullname" . }}-secret
  labels:
    {{- include "kaneo.labels" . | nindent 4 }}
spec:
  resyncInterval: {{ .Values.infisical.resyncInterval | default 60 }}
  authentication:
    kubernetesAuth:
      identityId: {{ .Values.infisical.identityId | quote }}
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-auth-sa
        namespace: infisical-operator-system
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug | default "homelab-k8s" | quote }}
        envSlug: {{ .Values.infisical.envSlug | default "prod" | quote }}
        secretsPath: {{ .Values.infisical.secretsPath | quote }}
  managedSecretReference:
    secretName: {{ .Values.infisical.secretName | default (printf "%s-secret" (include "kaneo.fullname" .)) }}
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Owner
    secretType: Opaque
{{- end }}
