---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  credentials.json: ""  # This will be populated by the setup script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: homelab-tunnel
    credentials-file: /etc/cloudflared/credentials/credentials.json
    origincert: /etc/cloudflared/cert.pem
    
    # Ingress rules will be managed by the tunnel controller
    ingress:
      # Catch-all rule (returns 404 for unmatched requests)
      - service: http_status:404
    
    # Optional: Enable metrics
    metrics: 0.0.0.0:8080
    
    # Optional: Enable logging
    loglevel: info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        command:
        - cloudflared
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: credentials
          mountPath: /etc/cloudflared/credentials
          readOnly: true
        - name: origin-cert
          mountPath: /etc/cloudflared/cert.pem
          subPath: cert.pem
          readOnly: true
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
        livenessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
      - name: credentials
        secret:
          secretName: cloudflare-tunnel-credentials
      - name: origin-cert
        secret:
          secretName: cloudflare-tunnel-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared
spec:
  selector:
    app: cloudflared
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
