---
# This file is a template - you need to replace the credentials.json content
# with your actual tunnel credentials from Cloudflare
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: cloudflare-tunnel
type: Opaque
data:
  # This is a placeholder - replace with your actual base64 encoded credentials
  # To get your credentials:
  # 1. Create a tunnel in Cloudflare dashboard
  # 2. Download the credentials.json file
  # 3. Base64 encode it: cat credentials.json | base64 -w 0
  # 4. Replace the content below
  credentials.json: e30K  # This is just an empty JSON object as placeholder
