# Secret will be created by the setup script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: homelab-tunnel
    credentials-file: /etc/cloudflared/credentials/credentials.json
    origincert: /etc/cloudflared/cert.pem
    
    # Static configuration - managed by ArgoCD
    # Dynamic ingress rules are managed by service-controller in cloudflared-ingress-config
    
    # Optional: Enable metrics
    metrics: 0.0.0.0:8080
    
    # Optional: Enable logging
    loglevel: info
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-ingress-config
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/managed-by: service-controller
data:
  ingress.yaml: |
    # Dynamic ingress rules managed by service-controller
    # This file is automatically updated when services are added/removed
    ingress:
      # Catch-all rule (returns 404 for unmatched requests)
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      initContainers:
      - name: config-merger
        image: mikefarah/yq:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "🔧 Merging static and dynamic configurations..."
          yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' /etc/cloudflared/config/config.yaml /etc/cloudflared/ingress/ingress.yaml > /shared/merged-config.yaml
          echo "✅ Configuration merged successfully"
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: ingress-config
          mountPath: /etc/cloudflared/ingress
          readOnly: true
        - name: shared-config
          mountPath: /shared
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        command:
        - cloudflared
        - tunnel
        - --config
        - /etc/cloudflared/merged/merged-config.yaml
        - run
        volumeMounts:
        - name: shared-config
          mountPath: /etc/cloudflared/merged
          readOnly: true
        - name: credentials
          mountPath: /etc/cloudflared/credentials
          readOnly: true
        - name: origin-cert
          mountPath: /etc/cloudflared/cert.pem
          subPath: cert.pem
          readOnly: true
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
        livenessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
      - name: ingress-config
        configMap:
          name: cloudflared-ingress-config
      - name: shared-config
        emptyDir: {}
      - name: credentials
        secret:
          secretName: cloudflare-tunnel-credentials
      - name: origin-cert
        secret:
          secretName: cloudflare-tunnel-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared
spec:
  selector:
    app: cloudflared
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
