---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: homelab-tunnel
    credentials-file: /etc/cloudflared/credentials/credentials.json
    
    # Ingress rules for your services
    ingress:
      # Homepage dashboard
      - hostname: homepage.buildin.group
        service: http://homepage.homepage.svc.cluster.local:80
      
      # n8n workflow automation
      - hostname: n9n.buildin.group
        service: http://n8n.n8n.svc.cluster.local:80
      
      # Argo CD GitOps
      - hostname: argocd.buildin.group
        service: http://argocd-server.argocd.svc.cluster.local:80
      
      # Catch-all rule (optional - returns 404 for unmatched requests)
      - service: http_status:404
    
    # Optional: Enable metrics
    metrics: 0.0.0.0:8080
    
    # Optional: Enable logging
    loglevel: info
