# Example Service Configurations
# Copy these examples to your service definitions

---
# Example 1: Expose Homepage to the internet
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  annotations:
    # This annotation will make the service accessible at https://homepage.yourdomain.com
    cloudflare.com/tunnel-hostname: "homepage.yourdomain.com"
spec:
  selector:
    app: homepage
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP

---
# Example 2: Expose n8n to the internet
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
  annotations:
    # This annotation will make the service accessible at https://n8n.yourdomain.com
    cloudflare.com/tunnel-hostname: "n8n.yourdomain.com"
spec:
  selector:
    app: n8n
  ports:
  - port: 5678
    targetPort: 5678
  type: ClusterIP

---
# Example 3: Expose ArgoCD to the internet
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    # This annotation will make the service accessible at https://argocd.yourdomain.com
    cloudflare.com/tunnel-hostname: "argocd.yourdomain.com"
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

---
# Example 4: Longhorn - INTERNAL ONLY (no annotation)
apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  # NO cloudflare.com/tunnel-hostname annotation = INTERNAL ONLY
  # This service will only be accessible through MetalLB or port-forwarding
spec:
  selector:
    app: longhorn-frontend
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer  # Use MetalLB for internal access

---
# Example 5: Grafana - Expose to internet
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    # This annotation will make the service accessible at https://grafana.yourdomain.com
    cloudflare.com/tunnel-hostname: "grafana.yourdomain.com"
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP

---
# Example 6: Prometheus - INTERNAL ONLY (no annotation)
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
  # NO cloudflare.com/tunnel-hostname annotation = INTERNAL ONLY
  # This service will only be accessible through MetalLB or port-forwarding
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
  - port: 80
    targetPort: 9090
  type: LoadBalancer  # Use MetalLB for internal access
