---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel

resources:
  - namespace.yaml
  - cloudflared-deployment.yaml
  - cloudflared-config.yaml
  - cloudflared-service.yaml
  - create-tunnel-dns.yaml
