apiVersion: v1
kind: Service
metadata:
  name: whisper-asr
  namespace: speakr
  labels:
    app: whisper-asr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: whisper-asr


