apiVersion: apps/v1
kind: Deployment
metadata:
  name: speakr
  namespace: speakr
  labels:
    app: speakr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speakr
  template:
    metadata:
      labels:
        app: speakr
    spec:
      containers:
        - name: speakr
          image: ronganam/speakr:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8899
              name: http
          env:
            - name: LOG_LEVEL
              value: "ERROR"
            - name: TEXT_MODEL_BASE_URL
              value: "https://api.openai.com/v1"
            - name: TEXT_MODEL_NAME
              value: "gpt-5-mini"
            - name: GPT5_REASONING_EFFORT
              value: "medium"
            - name: GPT5_VERBOSITY
              value: "medium"
            - name: USE_ASR_ENDPOINT
              value: "true"
            - name: ASR_BASE_URL
              value: "http://whisper-asr:9000"
            - name: ALLOW_REGISTRATION
              value: "false"
            - name: SUMMARY_MAX_TOKENS
              value: "8000"
            - name: CHAT_MAX_TOKENS
              value: "5000"
            - name: TIMEZONE
              value: "Asia/Jerusalem"
            - name: ENABLE_CHUNKING
              value: "false"
            - name: CHUNK_LIMIT
              value: "20MB"
            - name: CHUNK_OVERLAP_SECONDS
              value: "3"
            - name: ADMIN_USERNAME
              value: "ronganam"
            - name: ADMIN_EMAIL
              value: "ronganam@gmail.com"
            - name: ENABLE_INQUIRE_MODE
              value: "true"
            - name: ENABLE_AUTO_PROCESSING
              value: "false"
            - name: AUTO_PROCESS_MODE
              value: "admin_only"
            - name: AUTO_PROCESS_WATCH_DIR
              value: "/data/auto-process"
            - name: AUTO_PROCESS_CHECK_INTERVAL
              value: "30"
            - name: SQLALCHEMY_DATABASE_URI
              value: "sqlite:////data/instance/transcriptions.db"
            - name: UPLOAD_FOLDER
              value: "/data/uploads"
            - name: TEXT_MODEL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: speakr-config
                  key: text_model_api_key
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: speakr-config
                  key: admin_password
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 4Gi
          volumeMounts:
            - name: instance
              mountPath: /data/instance
            - name: uploads
              mountPath: /data/uploads
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 3
      volumes:
        - name: instance
          persistentVolumeClaim:
            claimName: speakr-instance
        - name: uploads
          persistentVolumeClaim:
            claimName: speakr-uploads
