apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speakr-instance
  namespace: speakr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: longhorn
