apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speakr-uploads
  namespace: speakr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: longhorn
