apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speakr-asr-cache
  namespace: speakr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn


