apiVersion: v2
name: twenty
version: 0.1.0
dependencies:
  - name: app-blueprint
    alias: server
    version: "0.1.0"
    repository: "file://../_blueprint"
  - name: app-blueprint
    alias: worker
    version: "0.1.0"
    repository: "file://../_blueprint"
  - name: app-blueprint
    alias: db
    version: "0.1.0"
    repository: "file://../_blueprint"
  - name: app-blueprint
    alias: redis
    version: "0.1.0"
    repository: "file://../_blueprint"
