apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gilartworks-portfolio-infisical-secret
  namespace: gilartworks-portfolio
spec:
  # The host URL of your Infisical instance
  hostAPI: https://infisical.buildin.group
  
  # The secret containing the Machine Identity Token
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homelab-k8s" # REPLACE THIS
        envSlug: "prod"
        secretsPath: "gilartworks-portfolio"
      credentialsRef:
        secretName: infisical-auth
        clientIdKey: clientId
        clientSecretKey: clientSecret

  # Where to put the synced secrets
  managedSecretReference:
    secretName: gilartworks-portfolio-secret # The existing secret name expected by deployment
    creationPolicy: Owner
    secretType: Opaque
