apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gilartworks-portfolio-infisical-secret
  namespace: gilartworks-portfolio
spec:
  hostAPI: https://infisical.buildin.group
  
  authentication:
    kubernetesAuth:
      # The Identity ID from Infisical (Access Control -> Identities -> <Your Identity>)
      identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
      
      # The Service Account to use for authentication
      serviceAccountRef:
        name: default
        namespace: gilartworks-portfolio
        
      secretsScope:
        projectSlug: "homelab-k8s"
        envSlug: "prod"
        secretsPath: "homelab-k8s"

  managedSecretReference:
    secretName: gilartworks-portfolio-secret
    secretNamespace: gilartworks-portfolio
    creationPolicy: Owner
    secretType: Opaque
