apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gilartworks-portfolio-infisical-secret
  namespace: gilartworks-portfolio
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      # The Identity ID from Infisical (Access Control -> Identities -> <Your Identity>)
      identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
      
      # Automatically create a token for the service account (Required for K8s 1.24+)
      autoCreateServiceAccountToken: true

      # The Service Account to use for authentication
      serviceAccountRef:
        name: infisical-auth-sa
        namespace: infisical-operator-system
        
      secretsScope:
        projectSlug: "homelab-k8s"
        envSlug: "prod"
        secretsPath: "gilartworks-portfolio"

  managedSecretReference:
    secretName: gilartworks-portfolio-secret
    secretNamespace: gilartworks-portfolio
    creationPolicy: Owner
    secretType: Opaque
