app-blueprint:
  image:
    repository: registry.ganam.app/gilartworks-portfolio
    tag: "5.0"

  containerPort: 3000

  dns:
    hostname: portfolio.gilartworks.com
    exposure: public

  homepage:
    enabled: false

  volumes:
    - name: assets-local
      size: 2Gi
      mountPath: /app/assets
      storageClass: local-path
    - name: uploads-local
      size: 128Mi
      mountPath: /app/uploads
      storageClass: local-path

  infisical:
    enabled: true
    identityId: "646edad3-7cfd-466a-b6cd-6114b3682e3c"
    secretsPath: "/gilartworks-portfolio"
    secretName: gilartworks-portfolio-secret

  env:
    NODE_ENV: "production"

  extraEnv:
    - name: ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: gilartworks-portfolio-secret
          key: admin-password

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 30m
      memory: 200Mi
