apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: mqtt
  labels:
    app: mqtt
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: mqtt.ganam.app
    exposure.service-controller.io/type: internal
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
    app: mqtt
